"use client";

import { Navbar, SearchBar } from "@/components";
import { useFetch } from "@/hooks/useFetch";
import { setCompanies } from "@/store/features/delivery/deliverySlice";
import { useAppDispatch } from "@/store/store";
import "@/styles/globals.css";
import { poppins } from "@/utils/fonts";
import { usePathname } from "next/navigation";
import { useEffect } from "react";
import { Toaster } from "react-hot-toast";
import Providers from "../components/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const { fetchRequest } = useFetch();
  const dispatch = useAppDispatch();

  useEffect(() => {
    const fetchCompanies = async () => {
      const companies = await fetchRequest("/delivery-companies");
      console.log(companies);
      dispatch(setCompanies(companies));
    };
    fetchCompanies();
  }, []);

  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          {!pathname.startsWith("/auth") &&
          !pathname.startsWith("/delivery") ? (
            <>
              <SearchBar />
              <Navbar />
            </>
          ) : null}
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
